//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int Id { get; set; }
        public string CarName { get; set; }
        public int Engine { get; set; }
        public int Color { get; set; }
        public int State { get; set; }
        public int CarMileage { get; set; }
        public int Year { get; set; }
    
        public virtual Colors Colors { get; set; }
        public virtual Engines Engines { get; set; }
        public virtual States States { get; set; }
    }
}
